# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcdef154af8cfbb6040ec4a19472ce66d133441db224c944bf72657754a800abf237553275837ae2b7a5710d98d1167cfa10df462cd0a814c831c4b072b55ab3

test:
  secret_key_base: 093ad5dc346e9d10d432957e9d9acdcb7991303be3f3f46301f2b98f983d559443cf029ca8b425e6949ba73ecd663f471027d91e10e889ed50d9b5a88f90b1f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
